#!/usr/bin/env node
/* ──────────────────────────────────────────────────────────────────────────
   CIRO — Control + Integration + Runtime Operator.
   The automatic system-state writer for the AI PMO. Captures system truth at
   time T: merges the curated source-of-truth (ciro/state.config.json) with
   live git facts (timestamp, commit, recent changes) and emits:
     - memory/system_state.json   (structured State Memory Record — primary)
     - memory/COUNCIL_MEMORY.md   (human-readable high-level state log)
   Guardrails: CIRO records state only. It does not opine, propose strategy,
   expand scope, or predict the future.
   ────────────────────────────────────────────────────────────────────────── */

import { execSync } from 'node:child_process'
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUT_DIR = join(ROOT, 'memory')

function git(cmd, fallback = '') {
  try { return execSync(`git ${cmd}`, { cwd: ROOT, stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim() }
  catch { return fallback }
}

const LOOP_ORDER = ['signal', 'reasoning', 'decision', 'simulation', 'execution', 'feedback']
const MATURITY = [
  'Level 1 - Reporting',
  'Level 2 - Insight',
  'Level 3 - Decision Support',
  'Level 4 - Decision Automation',
  'Level 5 - Autonomous Execution',
]

// ── Load curated truth ──
const cfg = JSON.parse(readFileSync(join(ROOT, 'ciro/state.config.json'), 'utf8'))

// ── Capture live git facts ──
const commit = git('rev-parse --short HEAD', 'unknown')
const recentChanges = git('log -6 --pretty=%s', '')
  .split('\n')
  .map(s => s.trim())
  .filter(s => s && !/\[skip ci\]/i.test(s) && !/^ciro:/i.test(s))
  .slice(0, 5)

// ── Weakest stage = first inactive loop stage ──
const weakest = LOOP_ORDER.find(k => cfg.loop_status[k] === false) || null

// ── Build the System State Memory Record ──
const state = {
  timestamp: new Date().toISOString(),
  commit,
  system_state: {
    phase: cfg.phase,
    intelligence_level: cfg.intelligence_level,
    loop_status: cfg.loop_status,
    weakest_stage: weakest,
  },
  architecture_layers: cfg.architecture_layers,
  recent_changes: recentChanges,
  active_focus: cfg.active_focus,
  risk_state: cfg.risk_state,
  next_required_action: cfg.next_required_action,
}

mkdirSync(OUT_DIR, { recursive: true })
writeFileSync(join(OUT_DIR, 'system_state.json'), JSON.stringify(state, null, 2) + '\n')

// ── Render the human-readable Council Memory ──
const layerLine = (k, v) => `- \`${k}\` — **${v}**`
const stageMark = k => (cfg.loop_status[k] ? '✅' : '⬜')
const loopRow = LOOP_ORDER.map(k => `${stageMark(k)} ${k}`).join('  →  ')
const maturityList = MATURITY.map(m => (m === cfg.intelligence_level ? `- **▶ ${m}**` : `- ${m}`)).join('\n')

const md = `# Council Memory — System State Log

> CIRO snapshot · ${state.timestamp} · commit \`${commit}\`
> _High-signal state of the platform now. CIRO records; it does not interpret._

## 1. Current System State
The platform is a **${cfg.phase}** — ${cfg.intelligence_level}. Signal→Simulation is active; execution + feedback are not yet wired.

## 2. Active Architecture Layers
${Object.entries(cfg.architecture_layers).map(([k, v]) => layerLine(k, v)).join('\n')}

## 3. Recently Shipped Capabilities
${recentChanges.length ? recentChanges.map(c => `- ${c}`).join('\n') : '- (no recent changes captured)'}

## 4. System Loop Status
${loopRow}

**Weakest stage:** ${weakest ? `\`${weakest}\` (first inactive stage — the bottleneck)` : 'none — full loop active'}

## 5. Intelligence Maturity Level
${maturityList}

## 6. Active Build Focus
**${cfg.active_focus.primary_workstream}** — single priority workstream.
Blocked expansion: ${cfg.active_focus.blocked_expansion.map(b => `_${b}_`).join(' · ')}

## 7. Constraints / Risks
- **Primary risk:** ${cfg.risk_state.primary_risk}
- **Secondary risk:** ${cfg.risk_state.secondary_risk}
- **Stability:** ${cfg.risk_state.stability}

## 8. Next Critical Move
> ${cfg.next_required_action}

---
_Generated by CIRO (\`ciro/ciro.mjs\`). Full loop: Signal → Reason → Decide → Simulate → Execute → CIRO logs → Council updates → Signal._
`

writeFileSync(join(OUT_DIR, 'COUNCIL_MEMORY.md'), md)

console.log(`CIRO ✓ wrote memory/system_state.json + memory/COUNCIL_MEMORY.md @ ${state.timestamp} (${commit})`)
console.log(`  phase: ${cfg.phase} · ${cfg.intelligence_level} · weakest stage: ${weakest || 'none'}`)
